### ISSUE TITLE
HI DEVS

### ISSUE THREAD

**Issue by calcossmonkey** [Notplayingallday383/z1g-project#1]
so uh I just wanna say hi no issue only cus u made this amazing thing although I do have to say since replit is blocked at my school I have to use the GitHub link being
https://z1g-project.github.io/Terbium/static/index.html
none of the links or proxies are working.. kinda an issue I tried to code my own but I'm not that smart
anyways thanks for reading 
please create more alternative links pls

**Comment by calcossmonkey** [comment]
oh btw i should have put this on terbium my bad bruh LOL

**Comment by Notplayingallday383** [comment]
no worries it all good. however since you were unable to see the replit post I figured out the crashing and im starting to port some proxy based websites from replit to glitch and while I work on Terbium compatability you can try out BruhProx 6: https://bruhprox.glitch.me which should probably be unblocked (for the most part)

**Comment by calcossmonkey** [comment]
thanks man sorry for the bother ik u probably got more important things to be doing but love your proxies and the whole idea lol
